name: Contest Tracker Automation

on:
  schedule:
    # Run daily contest update at midnight UTC
    - cron: "0 0 * * *"
    # Run solution fetching every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  update-contests:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 0 * * *' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Daily Contest Update
        run: |
          curl -X POST ${{ secrets.VERCEL_URL }}/api/cron/update-contests \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            --fail-with-body

      - name: Log Success
        if: success()
        run: echo "✅ Daily contest update completed successfully"

      - name: Log Failure
        if: failure()
        run: echo "❌ Daily contest update failed"

  fetch-solutions:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 */6 * * *' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Fetch YouTube Solutions
        run: |
          curl -X POST ${{ secrets.VERCEL_URL }}/api/cron/fetch-solutions \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            --fail-with-body

      - name: Log Success
        if: success()
        run: echo "✅ Solution fetching completed successfully"

      - name: Log Failure
        if: failure()
        run: echo "❌ Solution fetching failed"

  # Run both jobs when manually triggered
  manual-update-all:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Manual Contest Update
        run: |
          echo "🚀 Running manual contest update..."
          curl -X POST ${{ secrets.VERCEL_URL }}/api/cron/update-contests \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            --fail-with-body

      - name: Wait before solution fetch
        run: sleep 10

      - name: Manual Solution Fetch
        run: |
          echo "🎯 Running manual solution fetch..."
          curl -X POST ${{ secrets.VERCEL_URL }}/api/cron/fetch-solutions \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            --fail-with-body

      - name: Completion Summary
        run: |
          echo "✅ Manual automation completed"
          echo "📊 Both contest updates and solution fetching finished"
