name: Daily Contest Update
on:
  schedule:
    # Run daily at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  update-contests:
    runs-on: ubuntu-latest
    steps:
      - name: Update Contest Data
        run: |
          curl -X POST https://contests-tracker.netlify.app/api/cron/update-contests \
            -H "Content-Type: application/json"
